apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: istio-system
    repoURL: https://github.com/rhdemomasters/istio-system-demo.git
    targetRevision: {{ .Values.spec.source.targetRevision }}
