apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators 
spec:
  channel: stable
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace 
  installPlanApproval: Automatic
  startingCSV: jaeger-operator.v1.13.1
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm
  namespace: openshift-operators 
spec:
  channel: stable
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: openshift-marketplace 
  installPlanApproval: Automatic
  startingCSV: kiali-operator.v1.0.7
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators 
spec:
  channel: '1.0'
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace 
  installPlanApproval: Automatic
  startingCSV: servicemeshoperator.v1.0.2
